export enum IpcChannel {
  ActiveBreakGet = "ACTIVE_BREAK_GET",
  BreakDefinitionPreviewsGet = "BREAK_DEFINITION_PREVIEWS_GET",
  AllowPostponeGet = "ALLOW_POSTPONE_GET",
  AppInitializedSet = "APP_INITIALIZED_SET",
  AppInitializedGet = "APP_INITIALIZED_GET",
  BreakEnd = "BREAK_END",
  BreakLengthGet = "BREAK_LENGTH_GET",
  BreakPostpone = "BREAK_POSTPONE",
  BreakStart = "BREAK_START",
  BreakWindowResize = "BREAK_WINDOW_RESIZE",
  BreakTrackingComplete = "BREAK_TRACKING_COMPLETE",
  BreakStatisticsGet = "BREAK_STATISTICS_GET",
  Error = "ERROR",
  LocalDataReset = "LOCAL_DATA_RESET",
  SoundEndPlay = "SOUND_END_PLAY",
  SoundStartPlay = "SOUND_START_PLAY",
  SettingsGet = "SETTINGS_GET",
  SettingsSet = "SETTINGS_SET",
  TimeSinceLastBreakGet = "TIME_SINCE_LAST_BREAK_GET",
}
